### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by crisdut**

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
Thank you! Why WIP?

**Comment by dr-orlovsky** [comment]
RGB Core/wallet were released previous night

**Comment by crisdut** [comment]
> RGB Core/wallet were released previous night

Yes, I know, and I started tests using these versions. I'm talking about releases of possible fixes and all that. I thought I'd go further into testing before we build a new version of these dependencies.

**Comment by crisdut** [comment]
Hi @dr-orlovsky, I will turn this PR ready to review, after we merge and release new version contains a following PRs:

- https://github.com/strict-types/strict-encoding/pull/10
- https://github.com/RGB-WG/rgb-core/pull/146

**Pull request merged**
